# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: false

r:
  - 3.5
  - 3.6
  - 4.0
  - devel

r_packages:
  - covr
  - devtools

addons:
  apt:
    packages:
      - libudunits2-dev

env:
  token: 6e04c811-b9e9-4846-9696-20cf5c215826
  global:
   - _R_CHECK_FORCE_SUGGESTS_: FALSE

after_success:
  - Rscript -e 'covr::codecov()'
